version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    # Don't install the package itself - just add it to path for autodoc
    # The sys.path.insert in conf.py handles making the package importable

